// Generated by wxt
export {};
declare global {
  const CircularButtonsContainer: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/CircularButtonsContainer",
  )["default"];
  const ContentScriptContext: typeof import(
    "wxt/client",
  )["ContentScriptContext"];
  const Footer: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/Footer",
  )["default"];
  const GITHUB_ROOT: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/constants",
  )["GITHUB_ROOT"];
  const Header: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/Header",
  )["default"];
  const InvalidMatchPattern: typeof import(
    "wxt/sandbox",
  )["InvalidMatchPattern"];
  const LANG_LIST: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/constants",
  )["LANG_LIST"];
  const LOGO_SVG: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/constants",
  )["LOGO_SVG"];
  const Layout: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/Layout",
  )["default"];
  const MatchPattern: typeof import("wxt/sandbox")["MatchPattern"];
  const SelectLang: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/SelectLang",
  )["default"];
  const SelectionOverlay: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/SelectionOverlay",
  )["default"];
  const Spinner: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/Spinner",
  )["default"];
  const TABCONTENT_CSS: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/constants",
  )["TABCONTENT_CSS"];
  const TAB_CSS: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/constants",
  )["TAB_CSS"];
  const TIMER_COUNT_LIMIT: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/constants",
  )["TIMER_COUNT_LIMIT"];
  const TSWIcon: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/TSWIcon",
  )["default"];
  const ThemeProvider: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/ThemeProvider",
  )["ThemeProvider"];
  const ThemeToggle: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/ThemeToggle",
  )["ThemeToggle"];
  const browser: typeof import("wxt/browser/chrome")["browser"];
  const createIframeUi: typeof import("wxt/client")["createIframeUi"];
  const createIntegratedUi: typeof import("wxt/client")["createIntegratedUi"];
  const createShadowRootUi: typeof import("wxt/client")["createShadowRootUi"];
  const defineAppConfig: typeof import("wxt/sandbox")["defineAppConfig"];
  const defineBackground: typeof import("wxt/sandbox")["defineBackground"];
  const defineConfig: typeof import("wxt")["defineConfig"];
  const defineContentScript: typeof import(
    "wxt/sandbox",
  )["defineContentScript"];
  const defineUnlistedScript: typeof import(
    "wxt/sandbox",
  )["defineUnlistedScript"];
  const defineWxtPlugin: typeof import("wxt/sandbox")["defineWxtPlugin"];
  const deleteTimerForDomain: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db",
  )["deleteTimerForDomain"];
  const explainCode: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["explainCode"];
  const explainSentence: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["explainSentence"];
  const explainWord: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["explainWord"];
  const fakeBrowser: typeof import("wxt/testing")["fakeBrowser"];
  const getAllTimersForDomains: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db",
  )["getAllTimersForDomains"];
  const injectScript: typeof import("wxt/client")["injectScript"];
  const ocr: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["ocr"];
  const pageRag: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["pageRag"];
  const readTimerForDomain: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db",
  )["readTimerForDomain"];
  const rewriteCode: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["rewriteCode"];
  const storage: typeof import("wxt/storage")["storage"];
  const summariseLink: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/ai",
  )["summariseLink"];
  const timerSchema: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db",
  )["timerSchema"];
  const timerStartedMap: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db",
  )["timerStartedMap"];
  const upsertTimerForDomain: typeof import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db",
  )["upsertTimerForDomain"];
  const useAppConfig: typeof import("wxt/client")["useAppConfig"];
  const useCallback: typeof import("react")["useCallback"];
  const useContext: typeof import("react")["useContext"];
  const useEffect: typeof import("react")["useEffect"];
  const useMemo: typeof import("react")["useMemo"];
  const useReducer: typeof import("react")["useReducer"];
  const useRef: typeof import("react")["useRef"];
  const useState: typeof import("react")["useState"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FloatingButton } from "/Users/huweihong/projects/tsw-hwh/tsw/src/components/SelectionOverlay";
  import(
    "/Users/huweihong/projects/tsw-hwh/tsw/src/components/SelectionOverlay"
  );
  // @ts-ignore
  export type { TimerForDomain } from "/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db";
  import("/Users/huweihong/projects/tsw-hwh/tsw/src/utils/db");
}
